### ISSUE TITLE
求jpg2pdf

### ISSUE THREAD

**Issue by lyscop** [anpho/ofd2pdf#1]
不需要界面，命令行运行，指定文件夹所有jpg，生成pdf文件，能旋转图片方向

**Comment by MerrickZ** [comment]
之前好像做过，代码找不着了……

**Comment by MerrickZ** [comment]
> 不需要界面，命令行运行，指定文件夹所有jpg，生成pdf文件，能旋转图片方向

你可以先试试 PDF补丁丁 这款软件，功能更全面一些。
![image](https://github.com/anpho/ofd2pdf/assets/1021332/ef4bec6a-d40d-4274-8041-5208cab2d1b5)

**Comment by MerrickZ** [comment]
命令行的jpg2pdf会另开新repo，这个issue我就先关闭了：）
